import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarApp from "@/components/Side-bar";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/providers/Theme-Provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShadCN Dashboard App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` flex ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
        <ThemeProvider
          attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        > 
        <SidebarProvider defaultOpen={defaultOpen}>
        <SidebarApp/>
        <main className="w-full">
            <Navbar/>
            <div className="px-6">
              {children}
            </div>
           
        </main>
        </SidebarProvider>
       </ThemeProvider>
      </body>
    </html>
  );
}
